### Try APIS for clients

### Create a client
POST http://localhost:3000/api/clients
Content-Type: application/json

{
  "idCard": "123",
  "name": "Daniel Felipe",
  "direction": "123 Armenia",
  "phoneNumber": "123",
  "email": "daniel@example.com",
  "password": "daniel123",
  "idCoupons": ["507f1f77bcf86cd799439011", "507f1f77bcf86cd799439012"],
  "idShoppingCart": "507f1f77bcf86cd799439013"
}

### Gets all clients
GET http://localhost:3000/api/clients

### Gets a Client by its id
GET http://localhost:3000/api/clients/66c4a42ebd27562d44530ba9

### Deletes a Client by its id
DELETE  http://localhost:3000/api/clients/66bf52bf2046b27428b702ef

### Try APIS for admins
### Create a admin
POST http://localhost:3000/api/admins
Content-Type: application/json

{
  "username": "Josedzzz",
  "password": "Josedzzz",
  "idClients": ["507f1f77bcf86cd799439011", "507f1f77bcf86cd799439012"],
  "active": true
}

### Gets all admins
GET http://localhost:3000/api/admins

### Gets a Admin by its id
GET http://localhost:3000/api/admins/66c4a44cbd27562d44530baa

### Deletes a Admin by its id
DELETE  http://localhost:3000/api/admins/66c4a44cbd27562d44530baa

### Try APIS for coupon
### Create a coupon
POST http://localhost:3000/api/coupons
Content-Type: application/json

{
  "discountPercent": 20.0,
  "expirationDate": "2024-12-31T23:59:59Z",
  "minPurchaseQuantity": 1.0,
  "isUsed": false
}

### Gets all coupons
GET http://localhost:3000/api/coupons

### Gets a Coupon by its id
GET http://localhost:3000/api/coupons/66c4a48cbd27562d44530bac

### Deletes a Coupon by its id
DELETE  http://localhost:3000/api/coupons/66c4a48cbd27562d44530bac

### Try APIS for distributionlocalities
### Create a distributionlocalities
POST http://localhost:3000/api/distributionlocalities
Content-Type: application/json

{
  "name": "Locality Name",
  "price": 100.0,
  "maxCapacity": 500
}

### Gets all distributionlocalities
GET http://localhost:3000/api/distributionlocalities

### Gets a DistributionLocalitie by its id
GET http://localhost:3000/api/distributionlocalities/66c4a49cbd27562d44530bad

### Deletes a DistributionLocalitie by its id
DELETE  http://localhost:3000/api/distributionlocalities/66c4a49cbd27562d44530bad

### Try APIS for Event
### Create a Event
POST http://localhost:3000/api/events
Content-Type: application/json

{
  "idDistributionLocality": "507f1f77bcf86cd799439015",
  "name": "Event Name",
  "address": "1234 Main St",
  "city": "City Name",
  "eventDate": "2024-12-31T20:00:00Z",
  "availablePurchase": true,
  "imageUrl": "https://example.com/event-image.jpg",
  "imapeDistributionLocality": "https://example.com/distribution-image.jpg"
}

### Gets all events
GET http://localhost:3000/api/events

### Gets a event by its id
GET http://localhost:3000/api/events/66c4a4f4bd27562d44530bae

### Deletes a Event by its id
DELETE  http://localhost:3000/api/events/66c4a4f4bd27562d44530bae

### Try APIS for Report
### Create a REport
POST http://localhost:3000/api/reports
Content-Type: application/json

{
  "sellDistributionLocalityes": {
    "Locality1": 150,
    "Locality2": 200
  },
  "profit": 50000.0
}

### Gets all reports
GET http://localhost:3000/api/reports

### Gets a Report by its id
GET http://localhost:3000/api/reports/66c4a50bbd27562d44530baf

### Deletes a Report by its id
DELETE  http://localhost:3000/api/reports/66c4a50bbd27562d44530baf

### Try APIS for ShoppingCart
### Create a REport
POST http://localhost:3000/api/shoppingcarts
Content-Type: application/json

{
  "idTickets": ["507f1f77bcf86cd799439011", "507f1f77bcf86cd799439012"],
  "totalPrice": 150.0,
  "idClient": "507f1f77bcf86cd799439013"
}

### Gets all ShoppingCarts
GET http://localhost:3000/api/shoppingcarts

### Gets a ShoppingCart by its id
GET http://localhost:3000/api/shoppingcarts/66c4a519bd27562d44530bb0

### Deletes a ShoppingCart by its id
DELETE  http://localhost:3000/api/shoppingcarts/66c4a519bd27562d44530bb0

### Try APIS for Tickets
# Create a ticket
POST http://localhost:3000/api/tickets
Content-Type: application/json

{
  "idClient": "507f1f77bcf86cd799439011",
  "idCoupon": "507f1f77bcf86cd799439012",
  "numTickets": 9,
  "locality": "Back Row",
  "netPaymentAmount": 100.00,
  "finalPaymentAmount": 90.00
}

### Get all tickets
GET http://localhost:3000/api/tickets

### Get a ticket by ID
GET http://localhost:3000/api/tickets/66bf53a72046b27428b702fd

### Delete a ticket by ID
DELETE http://localhost:3000/api/tickets/66bf53a72046b27428b702fd

### Try APIS for TicketOrders
### Create a ticket order
POST http://localhost:3000/api/ticketorders
Content-Type: application/json

{
  "idTicket": "507f1f77bcf86cd799439014",
  "purchaseDate": "2024-08-15T10:00:00Z"
}

### Get all ticket orders
GET http://localhost:3000/api/ticketorders

### Get a ticket order by ID
GET http://localhost:3000/api/ticketorders/66bf53d62046b27428b702ff

### Delete a ticket order by ID
DELETE http://localhost:3000/api/ticketorders/66bf53d62046b27428b702ff

### Login client
POST http://localhost:3000/api/clients/login
Content-Type: application/json

{
  "email": "daniel@example.com",
  "password": "daniel23"
}

### Login admin
POST http://localhost:3000/api/admins/login
Content-Type: application/json

{
  "email": "admin123",
  "password": "adminpassword"
}